Models/Savings.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
namespace FinanceChecker.Models
{
    public class Savings
    {
        [Key]
        public int SavingsID { get; set; }

        public Guid UserID { get; set; }

        [Required]
        public string? SavingsName { get; set; }

        [Required]
        [Range(0, double.MaxValue, ErrorMessage = "Savings amount must be a non-negative value.")]
        [DisplayFormat(DataFormatString = "{0:C}", ApplyFormatInEditMode = true)]
        public decimal Goal { get; set; }

        [Required]
        [Range(0, double.MaxValue, ErrorMessage = "Savings amount must be a non-negative value.")]
        [DisplayFormat(DataFormatString = "{0:C}", ApplyFormatInEditMode = true)]
        public decimal CurrentSavings { get; set; }

        [Required]
        public decimal Progress { get; set; }

        //validation for future dates using the CustomValidation attribute
        [DataType(DataType.Date)]
        [Display(Name = "Due Date")]
        [CustomValidation(typeof(Savings), "ValidateFutureDate")]
        public DateTime DueDate { get; set; }

        [DataType(DataType.Date)]
        public DateTime CreatedAt { get; set; }

        [DataType(DataType.Date)]
        public DateTime UpdatedAt { get; set; }

        public static ValidationResult ValidateFutureDate(DateTime date, ValidationContext context)
        {
            if (date.Date < DateTime.Now.Date)
            {
                return new ValidationResult("Due date must be a future date.");
            }
            return ValidationResult.Success;
        }
    }
}

Controllers/SavingsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FinanceChecker.Data;
using FinanceChecker.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace FinanceChecker.Controllers
{
    [Authorize]
    [AutoValidateAntiforgeryToken]

    public class SavingsController : Controller
    {
        private readonly ILogger<SavingsController> _logger;
        private readonly ApplicationDbContext _db;
        private readonly UserManager<IdentityUser> _userManager;

        public SavingsController(ILogger<SavingsController> logger, ApplicationDbContext db, UserManager<IdentityUser> userManager)
        {
            _logger = logger;
            _db = db;
            _userManager = userManager;
        }


        public async Task<IActionResult> Index()
        {
            // Retrieve savings goals for the current user from the database
            var user = await _userManager.GetUserAsync(User);
            var userId = GetCurrentUserId();
            if (user != null)
            {
                var savingsGoals = _db.Savings.Where(s => s.UserID == userId).ToList();
                return View(savingsGoals);
            }

            return View();
        }

        private Guid GetCurrentUserId()
        {
            return new Guid(User.FindFirst(System.Security.Claims.ClaimTypes.NameIdentifier).Value);
        }


            [HttpGet]
        public IActionResult CreateSavings()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateSavings(Savings savings)
        {
            if (ModelState.IsValid)
            {
                var user = await _userManager.GetUserAsync(User);
                var userId = GetCurrentUserId();

                if (user != null)
                {
                    savings.UserID = userId;
                    savings.CreatedAt = DateTime.Now;
                    savings.UpdatedAt = DateTime.Now;


                    // Calculate progress as a percentage of CurrentSavings to Goal
                    if (savings.Goal > 0)
                    {
                        savings.Progress = (savings.CurrentSavings / savings.Goal) * 100;
                    }
                    else
                    {
                        savings.Progress = 0;
                    }

                    _db.Savings.Add(savings);
                    _db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }

            return View("CreateSavings", savings);
        }

        [HttpGet]
        public IActionResult EditSavings(int id)
        {
            // Retrieve the savings goal from the database using the provided id
            var savings = _db.Savings.FirstOrDefault(s => s.SavingsID == id);

            if (savings == null)
            {
                return NotFound();
            }

            return View(savings);
        }

        [HttpPost]
        public IActionResult EditSavings(Savings updatedSavings)
        {
            if (ModelState.IsValid)
            {
                // Retrieve the original savings goal from the database using the provided id
                var originalSavings = _db.Savings.FirstOrDefault
                    (s => s.SavingsID == updatedSavings.SavingsID);

                if (originalSavings == null)
                {
                    return NotFound();
                }

                // Update the properties of the original savings goal
                originalSavings.Goal = updatedSavings.Goal;
                originalSavings.SavingsName = updatedSavings.SavingsName;
                originalSavings.DueDate = updatedSavings.DueDate;
                originalSavings.CurrentSavings = updatedSavings.CurrentSavings;
                originalSavings.UpdatedAt = DateTime.Now;

                // Calculate progress as a percentage of CurrentSavings to Goal
                if (originalSavings.Goal > 0)
                {
                    originalSavings.Progress = (originalSavings.CurrentSavings / originalSavings.Goal) * 100;
                }
                else
                {
                    originalSavings.Progress = 0;
                }

                // Update the savings goal in the database
                _db.Savings.Update(originalSavings);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }

            // If ModelState is not valid, calculate progress based on the current and goal savings
            if (updatedSavings.Goal > 0)
            {
                updatedSavings.Progress = (updatedSavings.CurrentSavings / updatedSavings.Goal) * 100;
            }
            else
            {
                updatedSavings.Progress = 0;
            }

            return View(updatedSavings);
        }


        public IActionResult DeleteSavings(int id)
        {
            // Retrieve the savings goal from the database using the provided id
            var savings = _db.Savings.FirstOrDefault(s => s.SavingsID == id);

            if (savings == null)
            {
                return NotFound();
            }

            _db.Savings.Remove(savings);
            _db.SaveChanges();

            return RedirectToAction("Index");
        }

    }
}

Views/Savings/CreateSavings.cshtml
@model FinanceChecker.Models.Savings
    <div class="container mt-4">
        <div class="row justify-content-center">
            <div class="card col-6">
                <div class="card-body">
                    <h2>Add New Savings Goal</h2>
                    <form asp-controller="Savings" asp-action="CreateSavings" method="post">
                        <div class="form-group">
                            <label for="SavingsName">Savings Name:</label>
                            <input asp-for="SavingsName" class="form-control" />
                            <span asp-validation-for="SavingsName" class="text-danger"></span>
                        </div>

                        <div class="form-group">
                            <label for="Goal">Target Amount:</label>
                            <input asp-for="Goal" class="form-control" value="0" />
                            <span asp-validation-for="Goal" class="text-danger"></span>
                        </div>

                        <div class="form-group">
                            <label for="DueDate">Due Date:</label>
                            <input asp-for="DueDate" type="date" class="form-control" />
                            <span asp-validation-for="DueDate" class="text-danger"></span>
                        </div>

                        <div class="form-group">
                            <label for="CurrentSavings">Current Savings:</label>
                            <input asp-for="CurrentSavings" class="form-control" value="0" />
                            <span asp-validation-for="CurrentSavings" class="text-danger"></span>
                        </div>
                        <br />
                        <div class="form-group">
                            <button type="submit" class="btn btn-primary">Set Savings Goal</button>
                        </div>

                        <input asp-for="Progress" type="hidden" value="0" />
                    </form>
                </div>
            </div>
        </div>
    </div>

Views/Savings/EditSavings.cshtml
@model FinanceChecker.Models.Savings
    <div class="container mt-4">
        <div class="row justify-content-center">
            <div class="card col-6">
                <div class="card-body">
                    <h2>Edit Savings Goal</h2>
                    <form asp-controller="Savings" asp-action="EditSavings" method="post">
                        <input type="hidden" asp-for="SavingsID" />

                        <div class="form-group">
                            <label for="SavingsName">Savings Name:</label>
                            <input asp-for="SavingsName" class="form-control" />
                            <span asp-validation-for="SavingsName" class="text-danger"></span>
                        </div>

                        <div class="form-group">
                            <label for="Goal">Goal:</label>
                            <input asp-for="Goal" class="form-control" value="@Model.Goal.ToString("0.00")" />
                            <span asp-validation-for="Goal" class="text-danger"></span>
                        </div>

                        <div class="form-group">
                            <label for="DueDate">Due Date:</label>
                            <input asp-for="DueDate" type="date" class="form-control" />
                            <span asp-validation-for="DueDate" class="text-danger"></span>
                        </div>

                        <div class="form-group">
                            <label for="CurrentSavings">Current Savings:</label>
                            <input asp-for="CurrentSavings" class="form-control" value="@Model.CurrentSavings.ToString("0.00")" />
                            <span asp-validation-for="CurrentSavings" class="text-danger"></span>
                        </div>

<br />                        <div class="form-group">
                            <button type="submit" class="btn btn-primary">Save Changes</button>
                        </div>

                        <input asp-for="Progress" type="hidden" />
                    </form>
                </div>
            </div>
        </div>
    </div>

Views/Savings/Index.cshtml
@model IEnumerable<Savings>

<div class="text-end mt-3">
    <a class="btn btn-primary" asp-area="" asp-controller="Savings" asp-action="CreateSavings">Add a New Saving Goal</a>
</div>

<h2>Savings Management</h2>

<div class="row">
    @foreach (var savings in Model)
    {
        <div class="col-md-4 mb-4">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">@savings.SavingsName</h5>
                    <p class="card-text">Target Amount: £@savings.Goal.ToString("0.00")</p>
                    <p class="card-text">Amount Saved: £@savings.CurrentSavings.ToString("0.00")</p>
                    <div class="progress">
                        <div class="progress-bar progress-bar-fill" role="progressbar" style="width: @savings.Progress.ToString("0.00")%" aria-valuenow="@savings.Progress" aria-valuemin="0" aria-valuemax="100">
                            @savings.Progress.ToString("0.00")%
                        </div>
                    </div>
                    <p class="card-text">Due Date: @savings.DueDate.ToShortDateString()</p>
                    <div class="card-body d-flex justify-content-end">
                        <a asp-controller="Savings" asp-action="EditSavings" asp-route-id="@savings.SavingsID" class="btn btn-primary btn-sm mx-1" title="Edit"><i class="bi bi-pencil-square"></i></a>
                        <a asp-controller="Savings" asp-action="DeleteSavings" asp-route-id="@savings.SavingsID" class="btn btn-danger btn-sm mx-1" title="Delete"><i class="bi bi-trash-fill"></i></a>
                    </div>
                    </div>
                </div>
        </div>
        <br />
    }
</div>
<br />
<style>
    .progress-bar {
        width: 100%;
        height: 30px;
        background-color: #e0e0e0;
        border-radius: 4px;
        overflow: hidden;
    }

    .progress-bar-fill {
        height: 100%;
        background-color: green;
        width: 0;
        transition: width 0.3s;
    }
</style>

<script>function updateProgressBarColor(progressElement) {
        const progress = parseFloat(progressElement.style.width);
        if (progress >= 100) {
            progressElement.style.backgroundColor = 'blue';
        } else {
            progressElement.style.backgroundColor = 'green';
        }
    }

    const progressBars = document.querySelectorAll('.progress-bar-fill');
    progressBars.forEach(updateProgressBarColor);</script>
<br />