Models/Budget.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
namespace FinanceChecker.Models
{
    public class Budget
    {
        [Key]
        public int BudgetID { get; set; }

        public Guid UserID { get; set; }

        [Required]
        public string? CategoryName { get; set; }

        public int CategoryID { get; set; }

        [Required(ErrorMessage = "Please enter the amount.")]
        [Range(0, double.MaxValue, ErrorMessage = "Budget amount must be a non-negative value.")]
        [DataType(DataType.Currency)] public decimal Amount { get; set; }
        public decimal TotalTransactionsAmount { get; set; }

        [Required]
        public DateTime CreatedAt { get; set; }

        [Required]
        public DateTime UpdatedAt { get; set; }

        public decimal Progress { get; set; }


    }
}

Controllers/BudgetController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FinanceChecker.Data;
using FinanceChecker.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace FinanceChecker.Controllers
{
    [Authorize]
    [AutoValidateAntiforgeryToken]
    public class BudgetController : Controller
    {
        private readonly ILogger<BudgetController> _logger;
        private readonly ApplicationDbContext _db;
        private readonly UserManager<IdentityUser> _userManager;

        public BudgetController(ILogger<BudgetController> logger, ApplicationDbContext db, UserManager<IdentityUser> userManager)
        {
            _logger = logger;
            _db = db;
            _userManager = userManager;
        }


        public async Task<IActionResult> AddCategory()
        {
            var user = await _userManager.GetUserAsync(User);
            if (user != null)
            {
                var userId = user.Id;
                ViewBag.Id = userId;

                return View();
            }

            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult AddCategory(Category category)
        {
            if (string.IsNullOrEmpty(category.CategoryName))
            {
                TempData["error"] = "Category name cannot be null or empty.";
                return RedirectToAction("AddCategory");
            }

            if (ModelState.IsValid)
            {
                // Check if the category already exists in the Categories table
                var existingCategory = _db.Categories.FirstOrDefault(c => c.CategoryName.ToLower() == category.CategoryName.ToLower());
                if (existingCategory != null)
                {
                    TempData["error"] = "Category already exists.";
                    return RedirectToAction("AddCategory");
                }

                _db.Categories.Add(category);
                _db.SaveChanges();
                TempData["success"] = "Category saved successfully";
                return RedirectToAction("Index");
            }

            return View("AddCategory", category);
        }

        public async Task<IActionResult> Index()
        {
            var user = await _userManager.GetUserAsync(User);
            var userId = GetCurrentUserId();

            if (user != null)
            {
                var budgets = _db.Budgets.Where(b => b.UserID == userId).ToList();

                // Recalculate total transactions amount for each budget category
                foreach (var budget in budgets)
                {
                    var transactionsForCategory = _db.Transactions.Where
                        (t => t.Category == budget.CategoryName && t.UserID == userId
                        );
                    budget.TotalTransactionsAmount = transactionsForCategory.Sum(t => t.Amount);

                    if (budget.Amount > 0)
                    {
                        budget.Progress = (budget.TotalTransactionsAmount / budget.Amount) * 100;
                    }
                    else
                    {
                        budget.Progress = 0;
                    }
                }

                return View(budgets);
            }

            return View();
        }

        private Guid GetCurrentUserId()
        {
            return new Guid(User.FindFirst(System.Security.Claims.ClaimTypes.NameIdentifier).Value);
        }

        [HttpGet]
        public async Task<IActionResult> CreateBudget()
        {

            var user = await _userManager.GetUserAsync(User);
            if (user != null)
            {
                var userId = GetCurrentUserId();
                var budgets = _db.Budgets.Where(b => b.UserID == userId).ToList();
                var categories = _db.Categories.ToList();

                var budget = new Budget
                {
                    UserID = userId,
                };

                //ViewBag to pass the SelectList
                ViewBag.Categories = new SelectList(categories, "CategoryName", "CategoryName"); 
                return View(budget);
            }

            return View(new Budget()); // return an empty Budget model if user is null
        }

        [HttpPost]
        public async Task<IActionResult> CreateBudget(Budget budget)
        {
            var user = await _userManager.GetUserAsync(User);
            var userId = GetCurrentUserId();
            var existingBudget = _db.Budgets.FirstOrDefault(b => b.UserID == userId && b.CategoryName == budget.CategoryName);
            var category = _db.Categories.FirstOrDefault(c => c.CategoryName == budget.CategoryName);

            if (existingBudget != null)
            {
                ModelState.AddModelError("Budget.CategoryName", "Budget category already exists for this user.");
                var existingCategories = _db.Categories.ToList();
                ViewBag.Categories = new SelectList(existingCategories, "CategoryName", "CategoryName");
                TempData["error"] = "Budget category already exists for this user";
                return View(budget);
            }

            if (ModelState.IsValid)
            {
                budget.CategoryID = category.CategoryId; 

                budget.CreatedAt = DateTime.Now;
                budget.UpdatedAt = DateTime.Now;

                budget.Progress = 0;

                _db.Budgets.Add(budget);
                _db.SaveChanges();
                TempData["success"] = "Budget saved successfully";
                return RedirectToAction("Index");
            }


            var budgets = _db.Budgets.Where(b => b.UserID == userId).ToList();
            var categories = _db.Categories.ToList();

            foreach (var b in budgets)
            {
                var currentMonth = DateTime.Now.Month;
                var currentYear = DateTime.Now.Year;

                var transactionsForCategory = _db.Transactions
                    .Where(t => t.Category == b.CategoryName && t.UserID == userId &&
                                t.Date.Month == currentMonth && t.Date.Year == currentYear);



                b.TotalTransactionsAmount = transactionsForCategory.Sum(t => Math.Abs(t.Amount));

                if (Math.Abs(b.Amount) > 0)
                {
                    b.Progress = (b.TotalTransactionsAmount / Math.Abs(b.Amount)) * 100;
                }
                else
                {
                    b.Progress = 0;
                }
            }

            ViewBag.Categories = new SelectList(categories, "CategoryName", "CategoryName");

            return View(budget);
        }


        public IActionResult EditBudget(int id)
        {
            var budget = _db.Budgets.FirstOrDefault(b => b.BudgetID == id);

            if (budget == null)
            {
                return NotFound();
            }

            var categories = _db.Categories.ToList();
            ViewBag.Categories = new SelectList(categories, "CategoryName", "CategoryName");

            return View("EditBudget", budget);
        }

        [HttpPost]
        public async Task<IActionResult> EditBudget(Budget budget)
        {
            var user = await _userManager.GetUserAsync(User);
            var userId = GetCurrentUserId();
            var existingBudget = _db.Budgets.FirstOrDefault(b => b.BudgetID != budget.BudgetID && b.UserID == userId && b.CategoryName == budget.CategoryName);
            var category = _db.Categories.FirstOrDefault(c => c.CategoryName == budget.CategoryName);

            if (existingBudget != null)
            {
                ModelState.AddModelError("Budget.CategoryName", "Budget category already exists for this user.");
                var existingCategories = _db.Categories.ToList();
                ViewBag.Categories = new SelectList(existingCategories, "CategoryName", "CategoryName");
                TempData["error"] = "Budget category already exists for this user";
                return View(budget);
            }

            if (ModelState.IsValid)
            {
                budget.CategoryID = category.CategoryId;
                budget.UpdatedAt = DateTime.Now;


                if (Math.Abs(budget.Amount) > 0)
                {
                    budget.Progress = (budget.TotalTransactionsAmount / Math.Abs(budget.Amount)) * 100;
                }
                else
                {
                    budget.Progress = 0;
                }

                _db.Budgets.Update(budget);
                _db.SaveChanges();
                TempData["success"] = "Selected Budget updated successfully";
                return RedirectToAction("Index");
            }

            var categories = _db.Categories.ToList();
            ViewBag.Categories = new SelectList(categories, "CategoryName", "CategoryName");

            return View("EditBudget", budget);
        }


        public IActionResult DeleteBudget(int id)
        {
            var budget = _db.Budgets.FirstOrDefault(b => b.BudgetID == id);

            if (budget == null)
            {
                return NotFound();
            }

            _db.Budgets.Remove(budget);
            _db.SaveChanges();
            TempData["success"] = "Selected budget deleted successfully";

            return RedirectToAction("Index");
        }

    }

}

Views/Budget/AddCategory.cshtml
@model FinanceChecker.Models.Category

<div class="container mt-5">
    <div class="row">
        <div class="col-lg-6 mx-auto">
            <div class="card">
                <div class="card-body">
                    <h2 class="mb-4">Add Category</h2>
                    @if (TempData["error"] != null)
                    {
                        <div class="alert alert-danger mt-3">@TempData["error"]</div>
                    }
                    <form method="post" asp-action="AddCategory">
                        <div class="form-group">
                            <label for="CategoryName">Enter New Category Name:</label>
                            <input class="form-control" type="text" name="CategoryName">
                        </div>
                        <br>
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

Views/Budget/CreateBudget.cshtml
@model FinanceChecker.Models.Budget

<div class="text-end">
    <a class="btn btn-primary" asp-area="" asp-controller="Budget" asp-action="AddCategory">Add a New Category</a>
</div>
<div class="container mt-5">
    <div class="row">
        <div class="col-lg-8 mx-auto">
            <div class="card">
                <div class="card-body">
                    <h1 class="mb-4">Create Monthly Budget</h1>
                    @if (TempData["error"] != null)
                    {
                        <div class="alert alert-danger mt-3">@TempData["error"]</div>
                    }
                    <form asp-action="CreateBudget" asp-controller="Budget" method="post">
                        <input type="hidden" asp-for="UserID" />
                        <div class="form-group">
                            <label for="CategoryName">Category Name:</label>
                            <select asp-for="CategoryName" asp-items="(SelectList)ViewBag.Categories" class="form-control">
                                <option value="">-- Select Category --</option>
                            </select>
                        </div>
                        <div class="form-group">
                            <label for="Amount">Amount:</label>
                            <input asp-for="Amount" type="text" class="form-control" />
                            <span asp-validation-for="Amount" class="text-danger"></span>
                        </div>
                        <input type="hidden" asp-for="CategoryID" />
                        <input type="hidden" asp-for="TotalTransactionsAmount" />
                        <input type="hidden" asp-for="CreatedAt" />
                        <input type="hidden" asp-for="UpdatedAt" />
                        <input type="hidden" asp-for="Progress" />
                        <input type="submit" value="Create" class="btn btn-primary" />
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<style>
    .container {
        margin-top: 20px;
    }

    .form-group {
        margin-bottom: 20px;
    }

    .btn-primary {
        background-color: #007bff;
        border-color: #007bff;
    }

        .btn-primary:hover {
            background-color: #0056b3;
            border-color: #0056b3;
        }
</style>

Views/Budget/EditBudget.cshtml
@model FinanceChecker.Models.Budget

<div class="text-end mt-3">
    <a class="btn btn-primary" asp-area="" asp-controller="Budget" asp-action="AddCategory">Add a New Category</a>
</div>
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-6">
            <h4>Edit Budget</h4>
            <div class="card">
                <div class="card-body">
                    @if (TempData["error"] != null)
                    {
                        <div class="alert alert-danger mt-3">@TempData["error"]</div>
                    }
                    <form asp-action="EditBudget" asp-controller="Budget" method="post">
                        <input type="hidden" asp-for="BudgetID" />

                        <div class="form-group">
                            <label for="CategoryName">Category Name:</label>
                            <select asp-for="CategoryName" asp-items="(SelectList)ViewBag.Categories" class="form-control">
                                <option value="">-- Select Category --</option>
                            </select>
                            <span asp-validation-for="CategoryName" class="text-danger"></span>
                        </div>

                        <div class="form-group">
                            <label for="Amount">Amount:</label>
                            <input asp-for="Amount" type="text" class="form-control" value="@Model.Amount.ToString("0.00")" />
                            <span asp-validation-for="Amount" class="text-danger"></span>
                        </div>

                        <input type="hidden" asp-for="UserID" />
                        <input type="hidden" asp-for="CategoryID" />
                        <input type="hidden" asp-for="TotalTransactionsAmount" />
                        <input type="hidden" asp-for="CreatedAt" />
                        <input type="hidden" asp-for="UpdatedAt" />
                        <input type="hidden" asp-for="Progress" />
                        <br />
                        <input type="submit" value="Save Changes" class="btn btn-primary" />
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

Views/Budget/Index.cshtml
@model List<Budget>

    <div class="text-end mt-2">
        <a class="btn btn-primary" asp-area="" asp-controller="Budget" asp-action="CreateBudget">Add a New Budget</a>
    </div>

<div class="text-center">
    <h4>MONTHLY BUDGET</h4>
</div>

@foreach (var budget in Model)
{
    <div class="row justify-content-center mb-4">
        <div class="col-md-9">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">@budget.CategoryName</h5>
                    <div class="d-flex justify-content-between">
                        <p class="card-text">
                            <small>Budget: £@(budget.Amount.ToString("0.00"))</small>
                        </p>
                        <p class="card-text">
                            <small>Spent: £@(Math.Abs(budget.TotalTransactionsAmount).ToString("0.00"))</small>
                        </p>
                    </div>
                    <div class="progress" style="height: 40px;">
                        @if (budget.Amount > 0)
                        {
                            var progress = (Math.Abs(budget.TotalTransactionsAmount) / Math.Abs(budget.Amount)) * 100;
                            <div class="progress-bar progress-bar-fill" role="progressbar" style="width: @progress.ToString("0.00")%" aria-valuenow="@progress" aria-valuemin="0" aria-valuemax="100">
                                @progress.ToString("0.00")%
                            </div>
                        }
                        else
                        {
                            <div class="progress-bar progress-bar-fill" role="progressbar" style="width: 0%" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100">
                                0%
                            </div>
                        }
                    </div>
                    <div class="card-body d-flex justify-content-end">
                        <a asp-controller="Budget" asp-action="EditBudget" asp-route-id="@budget.BudgetID" class="btn btn-primary btn-sm mx-1" title="Edit"><i class="bi bi-pencil-square"></i></a>
                        <a asp-controller="Budget" asp-action="DeleteBudget" asp-route-id="@budget.BudgetID" class="btn btn-danger btn-sm mx-1" title="Delete"><i class="bi bi-trash-fill"></i></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <br />
}
<br />
<style>
    .progress-bar {
        width: 100%;
        background-color: #e0e0e0;
        border-radius: 4px;
        overflow: hidden;
        line-height: 40px;
    }

    @*height: 30px;

    *@
    .progress-bar-fill {
        height: 100%;
        background-color: green;
        width: 0;
        transition: width 0.3s;
    }
</style>

<script>function updateProgressBarColor(progressElement) {
            const progress = parseFloat(progressElement.style.width);
            if (progress >= 100) {
                progressElement.style.backgroundColor = 'red';
            } else {
                progressElement.style.backgroundColor = 'green';
            }
        }

        const progressBars = document.querySelectorAll('.progress-bar-fill');
        progressBars.forEach(updateProgressBarColor);</script>
<br />